// <auto-generated />
using System;
using Calendar3._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calendar3._0.Migrations
{
    [DbContext(typeof(CalendarContext))]
    partial class CalendarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calendar3._0.Model.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Appointment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Dates")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DaysBetween")
                        .HasColumnType("int");

                    b.Property<int?>("HowManyDays")
                        .HasColumnType("int");

                    b.Property<bool?>("MultipleDays")
                        .HasColumnType("bit");

                    b.Property<bool?>("Recurring")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Calendar");
                });
#pragma warning restore 612, 618
        }
    }
}
